# Generated by Django 5.1.4 on 2025-01-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0005_comment_is_approved_alter_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Rilis'),
        ),
    ]
